### ISSUE TITLE
Version.txt in subprojects

### ISSUE THREAD

**Issue by jamescway** [netzwerg/gradle-release-plugin#23]
Is it necessary to have a separate version.txt in all subprojects?  or am I doing something wrong? I have a version.txt in the main project root also.

```
A problem occurred evaluating root project 'zipkin'.
> Failed to apply plugin [id 'ch.netzwerg.release']
   > /Users/main_project/subproject/version.txt (No such file or directory)
```

**Comment by netzwerg** [comment]
No, you are doing it right, only the root project should contain a `version.txt`. Please also make sure that you **only apply the plugin in the root project**. Could this be the reason for your error?

**Comment by jamescway** [comment]
Thank you :smile: yes that worked. I moved the 'apply plugins...' out of the allprojects block and into the top level.
