### ISSUE TITLE
Could not determine the dependencies of task ':release'

### ISSUE THREAD

**Issue by sshahar1** [netzwerg/gradle-release-plugin#26]
Hi
I've added your plugin to my build.gradle file:
```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:1.2.3"
        classpath 'ch.netzwerg:gradle-release-plugin:1.1.0'
    }
}

plugins {
    //Gradle release plugin from: https://github.com/netzwerg/gradle-release-plugin
    id 'ch.netzwerg.release' version '1.1.0'
}

subprojects {
    group 'myGroup'

    version '1.0.0.0-SNAPSHOT'

    apply plugin: 'java'

    apply plugin: 'com.github.johnrengelman.shadow'
    apply plugin: 'maven'

    // Use Java 8
    sourceCompatibility = 1.8

    repositories {
        mavenLocal()
        jcenter()
        maven {
             // Repositories we use
        }
    }

    dependencies {

        // Dependencies we use
    }

}
````

When I run:
```shell
gradle tasks
```

I get the following error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':tasks'.
> > Could not determine the dependencies of task ':release'.

**Comment by netzwerg** [comment]
In a multi-project setup like yours, the root project must specify the release dependencies explicitly (see special note in [README](https://github.com/netzwerg/gradle-release-plugin#configuration)). You should thus add the following configuration e.g. at the very end of your `build.gradle` file:
```
release {
    dependsOn subprojects.build
}
```
You also might want to upgrade to the latest plugin release 1.2.0 (you are using 1.1.0).

**Comment by sshahar1** [comment]
Thanks, it works :-)
