### ISSUE TITLE
Build succeeds even if git push fails

### ISSUE THREAD

**Issue by jthurne** [netzwerg/gradle-release-plugin#27]
If the git push command fails (for example, because someone else pushed a commit up while the release was running), then the release task should fail, but it does not.  Instead, the build continues.

**Comment by jthurne** [comment]
I think changing [ReleaseTask Line 76](https://github.com/netzwerg/gradle-release-plugin/blob/master/src/main/groovy/ch/netzwerg/gradle/release/ReleaseTask.groovy#L76) to this should do the trick:

```
}.assertNormalExitValue()
```

See [org.gradle.api.Project:exec](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:exec(groovy.lang.Closure)) and [ExecResult](https://docs.gradle.org/current/javadoc/org/gradle/process/ExecResult.html)

**Comment by netzwerg** [comment]
Thanks for your report and the hint. I will look into it asap.

**Comment by netzwerg** [comment]
Fixed in 1.2.1 (available on [Bintray](https://bintray.com/netzwerg/gradle-plugins/gradle-release-plugin/1.2.1/view), [Gradle plugin central](https://plugins.gradle.org/plugin/ch.netzwerg.release) sync pending).

**Comment by jthurne** [comment]
@netzwerg Great! That was impressively fast!

Unfortunately, I just realized something about what I suggested and what you implemented: if the git command fails, then no output from the command will be logged, which would make it pretty hard to figure out why it failed.

Should be another pretty easy fix:

```
  def result = project.exec { //stuff }
  // print out the output (if any)
  result.assertNormalExitValue()
```

**Comment by netzwerg** [comment]
I tested it with a repo for which I removed all remotes but still have a `release { push = true }` configuration. The underlying git error is then written to the console:
```
:release
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
:release FAILED
```
It's not pretty, but should be sufficient to figure out why the build failed.

But you are correct, the output should also be logged  – thanks for the pointer!

**Comment by netzwerg** [comment]
Actually I **do** get log entries:
```
20:59:16.934 [ERROR] [system.err] fatal: 'origin' does not appear to be a git repository
20:59:16.935 [ERROR] [system.err] fatal: Could not read from remote repository.
20:59:16.936 [ERROR] [system.err]
20:59:16.936 [ERROR] [system.err] Please make sure you have the correct access rights
20:59:16.936 [ERROR] [system.err] and the repository exists.
```
>  no output from the command will be logged

Do you really see nothing at all?

**Comment by jthurne** [comment]
Your right! Sorry for the false alarm.
