### ISSUE TITLE
Master branch is moved after pushing with the plugin

### ISSUE THREAD

**Issue by Vad1mo** [netzwerg/gradle-release-plugin#28]
Hello Rahel,

I enabled to push on release and I now have the problem that the plugin is pushing to a new master branch. On the screenshot you see TAG 1.0.1. This was actually my master brach 19da802 it now became 1.0.1

![screenshot 2016-06-01 11 14 52](https://cloud.githubusercontent.com/assets/1492007/15704254/21cbfe74-27ea-11e6-90d2-755bd922686d.png)

On the second screenshot you can see that the current master is a complete new branch. 

![screenshot 2016-06-01 11 16 39](https://cloud.githubusercontent.com/assets/1492007/15704297/534ac408-27ea-11e6-9f89-a4b0589fd1ed.png)

Jenkins is checking out the code in this way

```
Checking out Revision 19da802c997053214cef316e895e018089286c11 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 19da802c997053214cef316e895e018089286c11 # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b master 19da802c997053214cef316e895e018089286c11
 > git rev-list 19da802c997053214cef316e895e018089286c11 # timeout=10
```

Is this normal behavior

**Comment by netzwerg** [comment]
I am not quite sure whether I am following: Why are there at least 5 identical "Release v1.0.3" commits? Is this a multi-module project? If yes, the plugin should only be applied once, in the root project (git tags are repository-wide, therefore versions should be repository-wide).

This is the Jenkins config I am using successfully:

![screen shot 2016-06-01 at 14 43 50](https://cloud.githubusercontent.com/assets/439387/15709927/c4afa98e-2807-11e6-8c35-49965e8c501a.png)

**Comment by Vad1mo** [comment]
ok I finally got it, the problem was with the multiple versions.

![screenshot 2016-06-01 17 12 32](https://cloud.githubusercontent.com/assets/1492007/15714758/1a0ac5bc-281c-11e6-9940-805294a6a4b0.png)
