### ISSUE TITLE
git executable output needs to be logged before exiting

### ISSUE THREAD

**Issue by stefanleh** [netzwerg/gradle-release-plugin#33]
commitVersionFile("Release v$project.version", releaseExtension) 

this leads to the problem that when git command is called it cant interprete correctly:

git commit -m Release v0.0.1 version.txt

vs

git commit -m "Release v0.0.1" version.txt

**Comment by stefanleh** [comment]
I've opened a pull request ...
https://github.com/netzwerg/gradle-release-plugin/pull/34

**Comment by netzwerg** [comment]
Thanks for the report and the PR.

> this leads to the problem that when git command is called it cant interprete correctly

Could you please specify

* how the problem manifests itself (build failure? truncated commit message?)
* on which platform/setup (git version?) it occurs
* possibly giving exacts steps of how to reproduce the problem

I am asking because nobody has ever had an issue with this and the code has been like this for ages...

**Comment by stefanleh** [comment]
git version 2.8.1.windows.1

14:37:29.002 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'git''. Working directory: D:\Projects\XYZ Command: git commit -m Release v0.0.1 version.txt

14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter]
14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':release'.
14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'git'' finished with non-zero exit value 1
14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter]
14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
14:37:29.344 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
14:37:29.344 [LIFECYCLE] [org.gradle.BuildResultLogger]
14:37:29.344 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED


gradlew --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Windows 10 10.0 amd64

**Comment by stefanleh** [comment]
But the same applies on our Teamcity build agent ....

**Comment by netzwerg** [comment]
Thanks, I will look into it.

**Comment by stefanleh** [comment]
def git(Object[] arguments) {
        LOGGER.debug("git $arguments")
        def output = new ByteArrayOutputStream()
        def result = project.exec {
            executable 'git'
            args arguments
            standardOutput output
            ignoreExitValue = true
        }
        // output result to debug
        String gitOutput = output.toString().trim()
        if (!gitOutput.isEmpty()) {
            LOGGER.debug(gitOutput)
        }
        // check if successful after logging
        result.assertNormalExitValue()
    }

I have changed the method for calling the git executable as throwing the error via "assertNormalExitValue()" surpressed logging of the output.

I get bad git exit status as i already have a commit wating for push.

15:50:21.504 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'git'' finished with exit value 1 (state: FAILED)
15:50:21.507 [DEBUG] [ch.netzwerg.gradle.release.ReleaseTask] On branch master
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

**Comment by netzwerg** [comment]
Thanks for the clarifications. Your changes with respect to logging make sense, thanks for updating the PR.

Concerning the quoting: Is this still an issue for you? If yes, we would need a platform-specific fix (possibly with more investigation/testing). If no, could you please create a new PR with just the logging changes – tia!

**Comment by netzwerg** [comment]
Release v1.2.5 including your logging changes should be available on Bintray jcenter soon...

**Comment by stefanleh** [comment]
Thank you very much.
