### ISSUE TITLE
Provide option to also create a release on GitHub

### ISSUE THREAD

**Issue by etiennestuder** [netzwerg/gradle-release-plugin#8]
I'm pretty sure you can do a release on GitHub through their REST API.
To be consistent, the same versions, titles, etc. should be used (where there is an overlap).

**Comment by netzwerg** [comment]
I have just published a first version on [Bintray](https://bintray.com/netzwerg/gradle-plugins/gradle-release-pub-plugin). Please have a look at the [README](https://github.com/netzwerg/gradle-release-pub-plugin/blob/master/README.md) and let me know if this conceptually suits your needs.

PS: ATM the plugin is only available on jcenter, inclusion in the central Gradle plugin repo is pending...

**Comment by etiennestuder** [comment]
I will give it a spin!

Once thing I'm wondering: why don't you programmatically apply the base plugin in the pub plugin? It would make the build script more concise and less potential for an accidental version conflict.

**Comment by netzwerg** [comment]
Thanks for pointing this out. Actually, I am applying the base plugin programmatically but couldn't get the transitive resolution to work: When building the pub plugin, the base plugin is declared as a compile dependency and things work out correctly. However, when applying the pub plugin, this transitive dependency is missing when the base plugin is not applied explicitly.

**Comment by netzwerg** [comment]
I just noticed that the compile dependency is missing in the [published POM](https://bintray.com/artifact/download/netzwerg/gradle-plugins/ch/netzwerg/gradle-release-pub-plugin/0.1.0/gradle-release-pub-plugin-0.1.0.pom). That explains why the transitive dependency resolution doesn't work...

**Comment by etiennestuder** [comment]
You have to apply the dependencies block before the plugindev block. See also:
https://github.com/etiennestuder/gradle-plugindev-plugin/issues/11

This is not an intended behavior of the plugindev plugin and I will investigate the reason for this. For now, changing the order in the script acts as a work-around.

**Comment by netzwerg** [comment]
Cool, thanks for the hint. I have changed the order and it works like a charm now!
I'm closing this issue -- feedback is welcome directly on the pub plugin repo.
